name: 'Submodules Sync'

on:
  schedule:
  - cron: "0 8 * * *"
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git config --global user.email "<your-email>"
          git config --global user.name "<your-name>"
          git commit -am "Update submodules"
          git push
