name: 'Submodules Sync'

on:
  schedule:
  - cron: "0 8 * * *"
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update submodules
        run: |
          git config --global user.email "action@noreply.github.com"
          git config --global user.name "action"
          git submodule update --init --recursive || echo "submodule is updated"
          git commit -am "Update submodules" && git push || echo "No changes to commit"
